### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by pepper-jk** [tao-shen/FEMNIST_pytorch#2]
This repository does not have a license.

Could you add a license, so we know if we can use your code for research?

[Here](https://choosealicense.com/) you can read up on different open licenses.

**Comment by tao-shen** [comment]
please feel free to use the code for research.

**Comment by pepper-jk** [comment]
Thanks, that is great to hear!

Would you still consider to add a license? That would really help us and any future users of the code.

**Comment by pepper-jk** [comment]
Thanks for choosing a license.
